### ISSUE TITLE
Need firm timeline for pilot script completion

### ISSUE THREAD

**Issue by ryan953** [des4maisons/superhappyfunpeople-quotes#7]
The pilot for this TV series has taken way too long to complete. We need firm deadlines as to when we'll see the first draft. I think optimistically that should be completed no later than the end of this year, which will give us a solid base to edit and plan against through the winter. Then we can start working on the character arch for the first two seasons and really kick this project into gear.
Ideally filming for season one would begin in the late summer months in Toronto and then complete by Christmas time.

@des4maisons does this sound reasonable? What extra resources are needed for you to meet these studio expectations?

**Comment by marvinpinto** [comment]
:+1:

**Comment by marvinpinto** [comment]
+1

**Comment by des4maisons** [comment]
@ryan953, your jokes are too hard to 1-up.

Closing out of humiliation.

**Comment by ryan953** [comment]
I hope Charlyne Yi is available for the first season. https://www.youtube.com/watch?v=24zAybnk8cY

cc @ysim
